version: '3.3'
services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: newsletter
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    expose:
      - 5432

networks:
  default:
    name: postgre-service_default